# Generated by Django 4.2.6 on 2023-12-30 18:52

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nomAcitivite",
                    models.CharField(max_length=24, unique=True, verbose_name="Nom"),
                ),
                (
                    "DescActivite",
                    models.CharField(max_length=24, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Activité",
                "verbose_name_plural": "Activités",
                "db_table": "activite",
            },
        ),
        migrations.CreateModel(
            name="ActiviteParClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SalleDeSport.activite",
                        verbose_name="Activité",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activité par Club",
                "verbose_name_plural": "Activités par club",
                "db_table": "activiteParClub",
            },
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nomClub",
                    models.CharField(max_length=24, unique=True, verbose_name="Nom"),
                ),
                (
                    "email",
                    models.EmailField(max_length=64, unique=True, verbose_name="Email"),
                ),
                (
                    "tel",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        region=None,
                        unique=True,
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "addressClub",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Adresse"
                    ),
                ),
                (
                    "ville",
                    models.CharField(max_length=64, unique=True, verbose_name="Ville"),
                ),
                (
                    "activite",
                    models.ManyToManyField(
                        through="SalleDeSport.ActiviteParClub",
                        to="SalleDeSport.activite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Club",
                "verbose_name_plural": "Clubs",
                "db_table": "club",
            },
        ),
        migrations.CreateModel(
            name="Cours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nomCours",
                    models.CharField(max_length=24, unique=True, verbose_name="Nom"),
                ),
                ("capacite", models.CharField(max_length=24, verbose_name="Capacité")),
                (
                    "description",
                    models.CharField(max_length=24, verbose_name="Description"),
                ),
                (
                    "activite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SalleDeSport.activite",
                        verbose_name="Activité",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cours",
                "verbose_name_plural": "Cours",
                "db_table": "cours",
            },
        ),
        migrations.CreateModel(
            name="Instructeur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=24, verbose_name="Nom")),
                ("prenom", models.CharField(max_length=64, verbose_name="Prénom")),
                (
                    "email",
                    models.EmailField(max_length=64, unique=True, verbose_name="Email"),
                ),
                (
                    "tel",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        region=None,
                        unique=True,
                        verbose_name="Téléphone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instructeur",
                "verbose_name_plural": "Instructeurs",
                "db_table": "instructeur",
            },
        ),
        migrations.CreateModel(
            name="ModePaiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "typeCarte",
                    models.CharField(max_length=24, verbose_name="Type du Carte"),
                ),
                (
                    "numeroCarte",
                    models.PositiveIntegerField(verbose_name="Numéro de la carte"),
                ),
                (
                    "dateExp",
                    models.PositiveIntegerField(verbose_name="Date d'expiration"),
                ),
                ("cvc", models.PositiveIntegerField(verbose_name="CVC")),
                (
                    "address",
                    models.PositiveIntegerField(verbose_name="Adresse de facturation"),
                ),
            ],
            options={
                "verbose_name": "Mode de paiement",
                "verbose_name_plural": "Modes de paiement",
                "db_table": "modepaiment",
            },
        ),
        migrations.CreateModel(
            name="TypeAbonnement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nomAbon",
                    models.CharField(
                        max_length=24, unique=True, verbose_name="Nom de l'abonnenment"
                    ),
                ),
                (
                    "dureAbon",
                    models.PositiveIntegerField(verbose_name="Durée (en mois)"),
                ),
                ("prixAbon", models.PositiveIntegerField(verbose_name="Prix")),
            ],
            options={
                "verbose_name": "Type d'abonnement",
                "verbose_name_plural": "Types d'abonnement",
                "db_table": "typeabonnement",
            },
        ),
        migrations.CreateModel(
            name="Seance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SalleDeSport.cours",
                        verbose_name="Cours",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seance Essai",
                "verbose_name_plural": "Seances d'essai",
                "db_table": "seanceEssai",
            },
        ),
        migrations.CreateModel(
            name="Membre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=24, verbose_name="Nom")),
                ("prenom", models.CharField(max_length=64, verbose_name="Prénom")),
                (
                    "email",
                    models.EmailField(max_length=64, unique=True, verbose_name="Email"),
                ),
                (
                    "tel",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        region=None,
                        unique=True,
                        verbose_name="Téléphone",
                    ),
                ),
                ("preferenceNotif", models.BooleanField(verbose_name="Notification")),
                (
                    "statutPayement",
                    models.CharField(max_length=16, verbose_name="Statut du payement"),
                ),
                (
                    "dateRenouvellement",
                    models.DateField(verbose_name="Date du Renouvellement"),
                ),
                (
                    "coursInscrits",
                    models.ManyToManyField(
                        related_name="membres",
                        to="SalleDeSport.cours",
                        verbose_name="Cours",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre",
                "verbose_name_plural": "Membres",
                "db_table": "membre",
            },
        ),
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=24, verbose_name="Nom")),
                ("prenom", models.CharField(max_length=64, verbose_name="Prénom")),
                (
                    "email",
                    models.EmailField(max_length=64, unique=True, verbose_name="Email"),
                ),
                (
                    "tel",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        region=None,
                        unique=True,
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "seanceEssai",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SalleDeSport.seance",
                        verbose_name="Séance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invité",
                "verbose_name_plural": "Invités",
                "db_table": "invite",
            },
        ),
        migrations.CreateModel(
            name="Equipement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomEquip", models.CharField(max_length=24, verbose_name="Nom")),
                ("dateAchat", models.DateField(verbose_name="Date d'achat")),
                ("dureeVie", models.PositiveIntegerField(verbose_name="Durée de vie")),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantité")),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SalleDeSport.club",
                        verbose_name="Club",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipement",
                "verbose_name_plural": "Equipements",
                "db_table": "equipement",
            },
        ),
        migrations.AddField(
            model_name="cours",
            name="instructeur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="SalleDeSport.instructeur",
                verbose_name="Instructeur",
            ),
        ),
        migrations.AddField(
            model_name="activiteparclub",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="SalleDeSport.club",
                verbose_name="Club",
            ),
        ),
    ]
