# Generated by Django 4.2.6 on 2024-03-29 01:17

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nomAcitivite",
                    models.CharField(max_length=32, unique=True, verbose_name="Nom"),
                ),
                (
                    "DescActivite",
                    models.CharField(max_length=64, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Activité",
                "verbose_name_plural": "Activités",
                "db_table": "activite",
            },
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nomClub",
                    models.CharField(max_length=24, unique=True, verbose_name="Nom"),
                ),
                (
                    "email",
                    models.EmailField(max_length=64, unique=True, verbose_name="Email"),
                ),
                (
                    "tel",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        region=None,
                        unique=True,
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "addressClub",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Adresse"
                    ),
                ),
                (
                    "ville",
                    models.CharField(
                        choices=[
                            ("Ag", "Agadir"),
                            ("Ca", "Casablanca"),
                            ("Mar", "Marakech"),
                            ("Ra", "Rabat"),
                            ("Tg", "Tanger"),
                        ],
                        max_length=64,
                        verbose_name="Ville",
                    ),
                ),
                (
                    "activites",
                    models.ManyToManyField(
                        blank=True, related_name="clubs", to="SalleDeSport.activite"
                    ),
                ),
            ],
            options={
                "verbose_name": "Club",
                "verbose_name_plural": "Clubs",
                "db_table": "club",
                "unique_together": {("nomClub", "ville")},
            },
        ),
        migrations.CreateModel(
            name="Cours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nomCours",
                    models.CharField(max_length=32, unique=True, verbose_name="Nom"),
                ),
                ("capacite", models.PositiveIntegerField(verbose_name="Capacité")),
                (
                    "description",
                    models.CharField(max_length=64, verbose_name="Description"),
                ),
                (
                    "activite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SalleDeSport.activite",
                        verbose_name="Activité",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cours",
                "verbose_name_plural": "Cours",
                "db_table": "cours",
            },
        ),
        migrations.CreateModel(
            name="Instructeur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=32, verbose_name="Nom")),
                ("prenom", models.CharField(max_length=64, verbose_name="Prénom")),
                (
                    "email",
                    models.EmailField(max_length=64, unique=True, verbose_name="Email"),
                ),
                (
                    "tel",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128,
                        region=None,
                        unique=True,
                        verbose_name="Téléphone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instructeur",
                "verbose_name_plural": "Instructeurs",
                "db_table": "instructeur",
            },
        ),
        migrations.CreateModel(
            name="ModePaiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "typeCarte",
                    models.CharField(
                        choices=[("Ma", "Mastercard"), ("Vi", "Visa")],
                        max_length=24,
                        verbose_name="Type du Carte",
                    ),
                ),
                (
                    "numeroCarte",
                    models.PositiveBigIntegerField(verbose_name="Numéro de la carte"),
                ),
                ("dateExp", models.DateField(verbose_name="Date d'expiration")),
                ("cvc", models.PositiveSmallIntegerField(verbose_name="CVC")),
                (
                    "address",
                    models.CharField(
                        max_length=86, verbose_name="Adresse de facturation"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mode de paiement",
                "verbose_name_plural": "Modes de paiement",
                "db_table": "modepaiment",
            },
        ),
        migrations.CreateModel(
            name="TypeAbonnement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nomAbon",
                    models.CharField(
                        max_length=24, unique=True, verbose_name="Nom de l'abonnenment"
                    ),
                ),
                (
                    "dureAbon",
                    models.PositiveIntegerField(verbose_name="Durée (en mois)"),
                ),
                ("prixAbon", models.PositiveIntegerField(verbose_name="Prix")),
            ],
            options={
                "verbose_name": "Type d'abonnement",
                "verbose_name_plural": "Types d'abonnement",
                "db_table": "typeabonnement",
            },
        ),
        migrations.CreateModel(
            name="Seance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateCours", models.DateField(verbose_name="Date de la séance")),
                ("heureDebut", models.TimeField(verbose_name="Début de la séance")),
                ("heureFin", models.TimeField(verbose_name="Fin de la séance")),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SalleDeSport.cours",
                        verbose_name="Cours",
                    ),
                ),
            ],
            options={
                "verbose_name": "Séance",
                "verbose_name_plural": "Séances",
                "db_table": "seanceEssai",
            },
        ),
        migrations.CreateModel(
            name="Membre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=32, verbose_name="Nom")),
                ("prenom", models.CharField(max_length=64, verbose_name="Prénom")),
                (
                    "email",
                    models.EmailField(max_length=64, unique=True, verbose_name="Email"),
                ),
                (
                    "tel",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128,
                        region=None,
                        unique=True,
                        verbose_name="Téléphone",
                    ),
                ),
                ("preferenceNotif", models.BooleanField(verbose_name="Notification")),
                (
                    "dateRenouvellement",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date du Renouvellement"
                    ),
                ),
                (
                    "coursInscrits",
                    models.ManyToManyField(
                        blank=True,
                        related_name="membres",
                        to="SalleDeSport.cours",
                        verbose_name="Cours Inscrits",
                    ),
                ),
                (
                    "modePaiement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SalleDeSport.modepaiement",
                        verbose_name="Mode de paiement",
                    ),
                ),
                (
                    "seancesReserves",
                    models.ManyToManyField(
                        blank=True,
                        related_name="seances",
                        to="SalleDeSport.seance",
                        verbose_name="Séances resérvées",
                    ),
                ),
                (
                    "typeAbon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SalleDeSport.typeabonnement",
                        verbose_name="Type d'abonnement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre",
                "verbose_name_plural": "Membres",
                "db_table": "membre",
            },
        ),
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=32, verbose_name="Nom")),
                ("prenom", models.CharField(max_length=64, verbose_name="Prénom")),
                (
                    "email",
                    models.EmailField(max_length=64, unique=True, verbose_name="Email"),
                ),
                (
                    "tel",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128,
                        region=None,
                        unique=True,
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "seanceEssai",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SalleDeSport.seance",
                        verbose_name="Séance d'essai",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invité",
                "verbose_name_plural": "Invités",
                "db_table": "invite",
            },
        ),
        migrations.AddField(
            model_name="cours",
            name="instructeur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="SalleDeSport.instructeur",
                verbose_name="Instructeur",
            ),
        ),
        migrations.CreateModel(
            name="Equipement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomEquip", models.CharField(max_length=32, verbose_name="Nom")),
                ("dateAchat", models.DateField(verbose_name="Date d'achat")),
                ("dureeVie", models.PositiveIntegerField(verbose_name="Durée de vie")),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantité")),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SalleDeSport.club",
                        verbose_name="Club",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipement",
                "verbose_name_plural": "Equipements",
                "db_table": "equipement",
                "unique_together": {("nomEquip", "club")},
            },
        ),
    ]
