# Generated by Django 4.2.6 on 2024-04-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SalleDeSport", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cours",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="cours_images/"),
        ),
    ]
