# Generated by Django 4.2.6 on 2023-12-31 00:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("SalleDeSport", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationCours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SalleDeSport.cours",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="seance",
            options={"verbose_name": "Séance", "verbose_name_plural": "Séances"},
        ),
        migrations.RemoveField(
            model_name="club",
            name="activite",
        ),
        migrations.AddField(
            model_name="club",
            name="activites",
            field=models.ManyToManyField(
                related_name="clubs", to="SalleDeSport.activite"
            ),
        ),
        migrations.AddField(
            model_name="membre",
            name="seancesReserves",
            field=models.ManyToManyField(
                related_name="membres",
                to="SalleDeSport.seance",
                verbose_name="Séances resérvées",
            ),
        ),
        migrations.AddField(
            model_name="seance",
            name="dateCours",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date de la séance"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seance",
            name="heureDebut",
            field=models.TimeField(
                default=django.utils.timezone.now, verbose_name="Début de la séance"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seance",
            name="heureFin",
            field=models.TimeField(
                default=django.utils.timezone.now, verbose_name="Fin de la séance"
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ActiviteParClub",
        ),
        migrations.DeleteModel(
            name="ModePaiement",
        ),
        migrations.AddField(
            model_name="reservationcours",
            name="membre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="SalleDeSport.membre"
            ),
        ),
    ]
