# Generated by Django 4.2.6 on 2024-05-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SalleDeSport", "0002_cours_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="typeabonnement",
            name="avantages",
            field=models.TextField(default="", verbose_name="Avantages"),
        ),
        migrations.AddField(
            model_name="typeabonnement",
            name="description",
            field=models.CharField(
                default="", max_length=64, verbose_name="Description"
            ),
        ),
    ]
