# Generated by Django 4.2.6 on 2024-05-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SalleDeSport", "0004_remove_modepaiement_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modepaiement",
            name="cvc",
            field=models.PositiveSmallIntegerField(unique=True, verbose_name="CVC"),
        ),
        migrations.AlterField(
            model_name="modepaiement",
            name="numeroCarte",
            field=models.PositiveBigIntegerField(
                unique=True, verbose_name="Numéro de la carte"
            ),
        ),
    ]
