# Generated by Django 4.2.6 on 2023-12-31 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("SalleDeSport", "0004_remove_membre_statutpayement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="activites",
            field=models.ManyToManyField(
                blank=True, related_name="clubs", to="SalleDeSport.activite"
            ),
        ),
        migrations.AlterField(
            model_name="membre",
            name="coursInscrits",
            field=models.ManyToManyField(
                blank=True,
                related_name="membres",
                to="SalleDeSport.cours",
                verbose_name="Cours",
            ),
        ),
        migrations.AlterField(
            model_name="membre",
            name="seancesReserves",
            field=models.ManyToManyField(
                blank=True,
                related_name="membres",
                to="SalleDeSport.seance",
                verbose_name="Séances resérvées",
            ),
        ),
    ]
