# Generated by Django 4.2.6 on 2023-12-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "SalleDeSport",
            "0005_alter_club_activites_alter_membre_coursinscrits_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="membre",
            name="dateRenouvellement",
            field=models.DateField(verbose_name="Date du Renouvellement"),
        ),
    ]
