# Generated by Django 4.2.6 on 2023-12-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SalleDeSport", "0006_alter_membre_daterenouvellement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membre",
            name="dateRenouvellement",
            field=models.DateField(null=True, verbose_name="Date du Renouvellement"),
        ),
    ]
