# Generated by Django 4.2.6 on 2024-05-03 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("SalleDeSport", "0006_jour_remove_seance_datecours_seance_jours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seance",
            name="heureFin",
        ),
    ]
