# Generated by Django 4.2.6 on 2024-05-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SalleDeSport", "0007_remove_seance_heurefin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activite",
            name="DescActivite",
            field=models.CharField(max_length=200, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="cours",
            name="description",
            field=models.CharField(max_length=128, verbose_name="Description"),
        ),
    ]
