# Generated by Django 4.2.6 on 2023-12-31 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("SalleDeSport", "0008_alter_membre_daterenouvellement"),
    ]

    operations = [
        migrations.AddField(
            model_name="membre",
            name="modePaiement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="SalleDeSport.modepaiement",
                verbose_name="Mode de paiement",
            ),
        ),
        migrations.AddField(
            model_name="membre",
            name="typeAbon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="SalleDeSport.typeabonnement",
                verbose_name="Type d'abonnement",
            ),
        ),
    ]
