# Generated by Django 4.2.6 on 2024-05-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SalleDeSport", "0008_alter_activite_descactivite_alter_cours_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cours",
            name="description",
            field=models.CharField(max_length=256, verbose_name="Description"),
        ),
    ]
