# Generated by Django 4.2.6 on 2023-12-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SalleDeSport", "0009_membre_modepaiement_membre_typeabon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membre",
            name="dateRenouvellement",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date du Renouvellement"
            ),
        ),
    ]
