# Generated by Django 4.2.6 on 2023-12-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SalleDeSport", "0010_alter_membre_daterenouvellement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cours",
            name="activite",
        ),
        migrations.RemoveField(
            model_name="cours",
            name="instructeur",
        ),
        migrations.AlterField(
            model_name="activite",
            name="DescActivite",
            field=models.CharField(max_length=64, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="activite",
            name="nomAcitivite",
            field=models.CharField(max_length=32, unique=True, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="cours",
            name="capacite",
            field=models.PositiveIntegerField(verbose_name="Capacité"),
        ),
        migrations.AlterField(
            model_name="cours",
            name="description",
            field=models.CharField(max_length=64, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="cours",
            name="nomCours",
            field=models.CharField(max_length=32, unique=True, verbose_name="Nom"),
        ),
    ]
