# Generated by Django 4.2.6 on 2024-05-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SalleDeSport", "0011_remove_seance_jours_seance_jour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seance",
            name="jour",
            field=models.CharField(
                choices=[
                    ("0", "Lundi"),
                    ("1", "Mardi"),
                    ("2", "Mercredi"),
                    ("3", "Jeudi"),
                    ("4", "Vendredi"),
                    ("5", "Samedi"),
                    ("6", "Dimanche"),
                ],
                max_length=12,
            ),
        ),
    ]
