# Generated by Django 4.2.6 on 2023-12-31 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "SalleDeSport",
            "0011_remove_cours_activite_remove_cours_instructeur_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cours",
            name="activite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="SalleDeSport.activite",
                verbose_name="Activité",
            ),
        ),
        migrations.AddField(
            model_name="cours",
            name="instructeur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="SalleDeSport.instructeur",
                verbose_name="Instructeur",
            ),
        ),
    ]
