# Generated by Django 4.2.6 on 2023-12-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SalleDeSport", "0013_alter_cours_activite_alter_cours_instructeur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipement",
            name="nomEquip",
            field=models.CharField(max_length=32, verbose_name="Nom"),
        ),
        migrations.AlterUniqueTogether(
            name="equipement",
            unique_together={("nomEquip", "club")},
        ),
    ]
