# Generated by Django 4.2.6 on 2023-12-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SalleDeSport", "0014_alter_equipement_nomequip_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invite",
            name="seanceEssai",
        ),
        migrations.AlterField(
            model_name="instructeur",
            name="nom",
            field=models.CharField(max_length=32, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="invite",
            name="nom",
            field=models.CharField(max_length=32, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="membre",
            name="nom",
            field=models.CharField(max_length=32, verbose_name="Nom"),
        ),
    ]
