# Generated by Django 4.2.6 on 2023-12-31 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "SalleDeSport",
            "0015_remove_invite_seanceessai_alter_instructeur_nom_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="seanceEssai",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="SalleDeSport.seance",
                verbose_name="Séance",
            ),
        ),
    ]
