# Generated by Django 4.2.6 on 2024-01-01 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("SalleDeSport", "0018_alter_invite_seanceessai"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membre",
            name="seancesReserves",
        ),
        migrations.DeleteModel(
            name="ReservationCours",
        ),
    ]
