# Generated by Django 4.2.6 on 2024-01-01 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("SalleDeSport", "0019_remove_membre_seancesreserves_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationCours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SalleDeSport.membre",
                    ),
                ),
                (
                    "seance",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SalleDeSport.seance",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="membre",
            name="seancesReserves",
            field=models.ManyToManyField(
                blank=True,
                through="SalleDeSport.ReservationCours",
                to="SalleDeSport.seance",
                verbose_name="Séances resérvées",
            ),
        ),
    ]
