# Generated by Django 4.2.6 on 2024-01-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SalleDeSport", "0020_reservationcours_membre_seancesreserves"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="ville",
            field=models.CharField(
                choices=[
                    ("Ag", "Agadir"),
                    ("Ca", "Casablanca"),
                    ("Ra", "Rabat"),
                    ("Tg", "Tanger"),
                ],
                max_length=64,
                unique=True,
                verbose_name="Ville",
            ),
        ),
        migrations.AlterField(
            model_name="membre",
            name="coursInscrits",
            field=models.ManyToManyField(
                blank=True,
                related_name="membres",
                to="SalleDeSport.cours",
                verbose_name="Cours Inscrits",
            ),
        ),
    ]
