# Generated by Django 4.2.6 on 2024-01-01 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("SalleDeSport", "0022_alter_club_ville"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="club",
            unique_together={("nomClub", "ville")},
        ),
    ]
