# Generated by Django 4.2.6 on 2024-01-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SalleDeSport", "0024_alter_club_ville"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modepaiement",
            name="cvc",
            field=models.PositiveSmallIntegerField(verbose_name="CVC"),
        ),
        migrations.AlterField(
            model_name="modepaiement",
            name="numeroCarte",
            field=models.PositiveBigIntegerField(verbose_name="Numéro de la carte"),
        ),
        migrations.AlterField(
            model_name="modepaiement",
            name="typeCarte",
            field=models.CharField(
                choices=[("Ma", "Mastercard"), ("Vi", "Visa")],
                max_length=24,
                verbose_name="Type du Carte",
            ),
        ),
    ]
