# Generated by Django 4.2.6 on 2024-01-01 23:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("SalleDeSport", "0025_alter_modepaiement_cvc_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="seance",
            unique_together={("dateCours", "heureDebut", "heureFin")},
        ),
    ]
