# Generated by Django 4.2.6 on 2024-01-02 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("SalleDeSport", "0026_alter_seance_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="seance",
            unique_together=set(),
        ),
    ]
