# Generated by Django 4.2.6 on 2024-01-03 18:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("SalleDeSport", "0027_alter_seance_unique_together"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ReservationCours",
            new_name="ReservationCour",
        ),
    ]
