# Generated by Django 4.2.6 on 2024-01-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SalleDeSport", "0029_remove_membre_seancesreserves"),
    ]

    operations = [
        migrations.AddField(
            model_name="membre",
            name="seancesReserves",
            field=models.ManyToManyField(
                blank=True,
                related_name="seances",
                to="SalleDeSport.seance",
                verbose_name="Séances resérvées",
            ),
        ),
    ]
