# Generated by Django 4.2.6 on 2024-01-27 01:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("SalleDeSport", "0030_membre_seancesreserves"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReservationCour",
        ),
    ]
